package domain.Repositories;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import mappers.IMapResultSetToEntity;
import domain.Privilege;
import domain.Role;
import domain.User;
import domain.uow.IUnitOfWork;

public class PrivilegeRepository extends RepositoryBase<Privilege> implements IPrivilegeRepository{

	public PrivilegeRepository(Connection connection,
			IMapResultSetToEntity<Privilege> mapper,
			IUnitOfWork uow) {
		super(connection,mapper, uow);
		// TODO Auto-generated constructor stub
	}

	@Override
	protected void setUpdateQuery(Privilege p) throws SQLException {
		// TODO Auto-generated method stub
		update.setInt(1, p.getRole_id());
		update.setString(2, p.getName());
		
	}

	@Override
	protected void setInsertQuery(Privilege p) throws SQLException {
		Role r = new Role();
		insert.setInt(1, p.getRole_id());
		insert.setString(2, p.getName());
	}

	@Override
	protected String tableName() {
		// TODO Auto-generated method stub
		return "privilege";
	}

	@Override
	protected String createTableSql() {
		// TODO Auto-generated method stub
		return "CREATE TABLE privilege("
				+"id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+"role_id bigint ," + "name VARCHAR(20)"
				+");";
	}

	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO privilege(role_id, name) VALUES (?,?)";
	}

	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE privilege SET role_id = ?, name = ? WHERE id = ?";
	}



}
